server:
  port: 8089
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: consul-server-route
          uri: lb://consul-server        #配置转发路径   lb：表示从注册中心获取服务的地址
          predicates:                   #请求路径断言，当网关ip的请求地址为/qpi/**时进行转发
            - Path=/api/**              #语法格式不要修改
          filters:                      #去除请求的前缀 StripPrefix= 1  表示去除 /api/
            - StripPrefix=1             #语法格式不要修改
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /health
        tags: gateway网关
#logging:
#  level:
#    org.springframework.cloud.gateway: TRACE
#    org.springframework.http.server.reactive: DEBUG
#    org.springframework.web.reactive: DEBUG
#    reactor.ipc.netty: DEBUG