server:
  port: 5000
spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trondb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
encrypt:
  key-store:
    location: classpath:/tron.keystore
    secret: zhenwuhuan
    alias: tronkey
    password: tronnort
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
auth:
  tokenValiditySeconds: 1200  #token存储到redis的过期时间
  clientId: test
  clientSecret: 123456
  cookieDomain: xuecheng.com
  cookieMaxAge: -1