server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#高可用配置：
#举例：
#server.port=8761  的服务器   defaultZone: 指向 8762
#server.port=8762  的服务器   defaultZone: 指向 8761
#然后client端的配置为  defaultZone: http://localhost:8761/eureka/,defaultZone: http://localhost:8762/eureka/