
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: http://192.168.1.110:8089/root/config.git
          username: root
          password: glr860308

  rabbitmq:
    host: my-rabbit
    addresses: 192.168.1.110
    port: 5672
    username: admin
    password: admin
#         basedir:   配置表本地git存放路径

# -a 表示git上的版本后缀名
# http://localhost:8000/configserver-a.yml   获取文件名configserver.yml的配置信息
# http://localhost:8000/configserver-dev.yml   可以根据后缀名来区分环境

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: '*'

#http://localhost:8000/actuator/bus-refresh
#注意能刷新的范围@ConfigurationProperties注解的配置信息